<?php
/**
 * Copyright [2017] Illia Voinov <ilya.voinov@yahoo.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
?>
<?php
/**
 * @var IV_NovaPoshta_Block_Carrier_Warehouses $this
 * @see IV_NovaPoshta_Block_Carrier_Warehouses
 */
?>
<?php
/** @var array|IV_NovaPoshta_Model_Resource_Entity_Warehouse_Collection $availableWarehouses */
$availableWarehouses = $this->getAvailableWarehouses();
?>
<select name="<?php echo $this->getWarehouseInputName(); ?>">
    <?php foreach ($availableWarehouses as $warehouse): ?>
        <?php /** @var IV_NovaPoshta_Model_Entity_Warehouse $warehouse */ ?>
        <option value="<?php echo $warehouse->getId() ?>"><?php echo $this->escapeHtml($warehouse->getDescription()); ?></option>
    <?php endforeach; ?>
</select>
