<?php
/**
 * Copyright [2017] Illia Voinov <ilya.voinov@yahoo.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
?>

<div class="checkout__right">

</div>

<div class="checkout__left">
    <form action="" id="co-shipping-form" class="form checkout-form">
        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />

        <h4 class="checkout-form__title"><?php echo $this->__('Addresses') ?></h4>

        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>

        <?php if ($this->customerHasAddresses()): ?>
            <div class="form__row col05">
                <?php echo $this->getAddressesHtmlSelect('shipping') ?>
                <label class="input_checkbox" for="billing-address-select">
                    <?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
                </label>
            </div>
        <?php endif; ?>

        <div id="shipping-new-address-form">
            <div class="form__row col2">
                <input type="tel" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
            </div>

            <h6 class="checkout-form__subtitle"><?php echo $this->__('Shipping Address') ?></h6>

            <div class="form__row col05">
                <?php echo $this->getCountryHtmlSelect('shipping') ?>
            </div>

            <div class="form__row col2">
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <input type="text" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
            </div>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <div class="form__row col2">
                <input type="text" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
            </div>
            <?php endfor; ?>

            <div class="form__row col2">
                <input type="text" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input js-city-google <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
            </div>

            <div class="form__row col2">
                <select id="shipping:region_id" name="shipping[region_id]"
                        placeholder="<?php echo $this->__('State/Province') ?>"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
                        class="input validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                    //<![CDATA[
                    $('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()
                        ->getRegionId() ?>");
                    //]]>
                </script>
                <input type="text" id="shipping:region" name="shipping[region]"
                       value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
                       class="input-text <?php echo $this->helper('customer/address')
                           ->getAttributeValidationClass('region') ?>" style="display:none;"/>
            </div>

            <div class="form__row col2">
                <input type="text" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
            </div>

            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
            <div class="form__row col5">
                <input type="checkbox" name="shipping[save_in_address_book]" value="1" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Save in address book')) ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="input_checkbox" />
                <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
            </div>
            <?php else:?>
                <input type="hidden" name="shipping[save_in_address_book]" value="1" />
            <?php endif;?>
        </div>

        <div class="form__action actions-container" id="shipping-buttons-container">
            <a href="#" class="btn btn-submit btn-gray" onclick="checkout.back(); return false;"><?php echo $this->__('Back') ?></a>

            <button type="button" class="btn btn-orange btn-submit input_submit" onclick="shipping.save()"><?php echo $this->__('Continue') ?></button>

            <span id="shipping-please-wait" class="please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
            </span>
        </div>
    </form>
</div>

<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...')) ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
